version: "3"

services:
  fdv_win_fed_30_s:
    environment:
        - FDV_GIT_REPO
        - FDV_GIT_BRANCH
        - FDV_CLEAN
        - FDV_CMAKE
    build: 
      context: fdv_win_fedora
      args:
         - FED_REL=30

    image:  fdv_win_fed30_i
    container_name: 'fdv_win_fed30_c'
    volumes:
            - win_fed30_v:/home/build/

volumes:
  win_fed30_v:
